name: task_management
description: "Task Management Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  intl: ^0.19.0

  # for environments
  flutter_dotenv: ^5.1.0

  # for svg
  flutter_svg: ^2.0.10+1

  # for network request
  dio: ^5.6.0

  # a dio interceptor for developer
  pretty_dio_logger: ^1.4.0

  # for creating api models
  json_annotation: ^4.9.0

  # for state management
  flutter_bloc: ^8.1.6

  # for dependency injection
  get_it: ^7.7.0

  # for functional programming and using Either 
  fpdart: ^1.1.0

  # Shared Preferences
  shared_preferences: ^2.3.3

  # for local database
  sqflite: ^2.3.3+1

  # path
  path: ^1.9.0

  # Dropdown
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - .env

  fonts:
    - family: MuseoSans100
      fonts:
        - asset: assets/fonts/museo_sans100.ttf
        - asset: assets/fonts/museo_sans100italic.ttf
          style: italic
    - family: MuseoSans300
      fonts:
        - asset: assets/fonts/museo_sans300.ttf
        - asset: assets/fonts/museo_sans300italic.ttf
          style: italic
    - family: MuseoSans500
      fonts:
        - asset: assets/fonts/museo_sans500.ttf
        - asset: assets/fonts/museo_sans500italic.ttf
          style: italic
    - family: MuseoSans700
      fonts:
        - asset: assets/fonts/museo_sans700.ttf
        - asset: assets/fonts/museo_sans700italic.ttf
          style: italic
    - family: MuseoSans900
      fonts:
        - asset: assets/fonts/museo_sans900.ttf
        - asset: assets/fonts/museo_sans900italic.ttf
          style: italic
